version: "3.8"

services:
  db:
    platform: linux/arm64/v8
    image: mysql:8.4
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpass}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-php_docker}
      MYSQL_USER: ${MYSQL_USER:-php_docker}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
    volumes:
      - db_data:/var/lib/mysql
      # โหลดสคริปต์ init จากโฟลเดอร์ใน repo (ไม่ใช่พาธ host แปลก ๆ)
      - ./db:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-p${MYSQL_ROOT_PASSWORD:-rootpass}"]
      interval: 10s
      timeout: 5s
      retries: 6
    networks: [app]

  www:
    platform: linux/arm64/v8
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      DB_NAME: ${MYSQL_DATABASE:-php_docker}
      DB_USER: ${MYSQL_USER:-php_docker}
      DB_PASS: ${MYSQL_PASSWORD:-password}
    ports:
      - "80:80"
      - "443:443"
      # ถ้าต้องการให้ออกพอร์ต 11380: ใช้ "11380:80" แทน
    networks: [app]

  phpmyadmin:
    platform: linux/arm64/v8
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      db:
        condition: service_healthy
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 256M
    ports:
      - "8001:80"
    networks: [app]

volumes:
  db_data:

networks:
  app:
    driver: bridge
